In [20]:
import numpy as np
import pandas as pd

import tensorflow as tf

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error

In [2]:
tf.__version__

'2.4.1'

#  Data Preprocessing

## Importing dataset

In [3]:
dataset = pd.read_csv('Folds5x2_pp.csv')
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [4]:
X = dataset.drop(['PE'], axis=1).values
y = dataset['PE'].values

In [5]:
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [6]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

## Splitting into train test

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Scaling the data

In [22]:
sc = StandardScaler()

X_train_s = sc.fit_transform(X_train)
X_test_s = sc.transform(X_test)

#  Building the ANN

## Initializing the ANN

In [8]:
# variable containing ANN
# which is an object of a sequential class

ann = tf.keras.models.Sequential()

In [9]:
type(ann)

tensorflow.python.keras.engine.sequential.Sequential

## Adding input layers and the 1st hidden layer

In [10]:
# adding fully connected layer
# which is an object of Dense class
# it automatically add's input layer

# units = no.of hidden neurons (experimental hyperparameter)
# input layer = no.of neurons 
# activation function = rectifier function

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Adding 2nd hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Adding the output layer

In [12]:
# units: output is single value so output neuron 1
# for regression no activation function

ann.add(tf.keras.layers.Dense(units=1))

#  Training ANN

## Compiling the ANN

In [13]:
# optimizer: optimizers such as gradiend descent, adam etc.
# loss: loss function for any regression problem is MSE
# metrics: evaluation metric

ann.compile(optimizer='adam', loss='mean_squared_error')

## Training the ANN on the training set

In [24]:
# batch_size: instead of compairing prediction to real result one by one,
# compare several predictions with several real values
# epochs: 1 epoch completes when all rows are used to train

ann.fit(X_train_s, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 3ms/step - loss: 181419.9688
Epoch 2/100
240/240 [==============================] - 1s 3ms/step - loss: 78364.6406
Epoch 3/100
240/240 [==============================] - 1s 3ms/step - loss: 24912.1289
Epoch 4/100
240/240 [==============================] - 1s 3ms/step - loss: 16018.9014
Epoch 5/100
240/240 [==============================] - 1s 3ms/step - loss: 11732.8623
Epoch 6/100
240/240 [==============================] - 1s 3ms/step - loss: 8116.8857
Epoch 7/100
240/240 [==============================] - 1s 3ms/step - loss: 5229.8203
Epoch 8/100
240/240 [==============================] - 1s 3ms/step - loss: 3272.9580
Epoch 9/100
240/240 [==============================] - 1s 3ms/step - loss: 2065.3293
Epoch 10/100
240/240 [==============================] - 1s 3ms/step - loss: 1321.3352
Epoch 11/100
240/240 [==============================] - 1s 3ms/step - loss: 864.7410
Epoch 12/100
240/240 [==============================] - 1s

#  Making the predictions and evaluating the model

Therefore, our ANN model predicts that this customer stays in the bank

## Predicting the test set resulta

In [25]:
y_pred = ann.predict(X_test_s)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[432.53 431.23]
 [457.7  460.01]
 [461.89 461.14]
 ...
 [468.   473.26]
 [443.17 438.  ]
 [461.55 463.28]]


## Root mean square error

In [26]:
np.sqrt(mean_squared_error(y_test, y_pred))

4.54943367232806