# Artificial Neural Network

## Importing libraries

In [48]:
import numpy as np
import pandas as pd

import tensorflow as tf

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

In [5]:
tf.__version__

'2.4.1'

# Data Preprocessing

## Importing dataset

In [7]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [13]:
X = dataset.drop(['RowNumber', 'CustomerId', 'Surname', 'Exited'], axis=1).values
y = dataset['Exited'].values

In [14]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [15]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

## Encoding categorical data

In [19]:
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [20]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [23]:
ct = ColumnTransformer(transformers=[('emcoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [24]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

## Splitting into train test

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Feature scaling

In [29]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [30]:
X_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [31]:
X_test

array([[-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  1.61255917]])

# Building the ANN

## Initializing the ANN

In [32]:
# variable containing ANN
# which is an object of a sequential class

ann = tf.keras.models.Sequential()

In [33]:
type(ann)

tensorflow.python.keras.engine.sequential.Sequential

## Adding input layers and the 1st hidden layer

In [34]:
# adding fully connected layer
# which is an object of Dense class
# it automatically add's input layer

# units = no.of hidden neurons (experimental hyperparameter)
# activation function = rectifier function

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Adding 2nd hidden layer

In [35]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

## Adding the output layer

In [36]:
# since dependent variable is a binary units=1
# in case dependent variable has 3 categories then units=3
# sigmoid activation function for output which gives probabilities
# for multi-class classsification use softmax activation function

ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# training ANN

## Compiling the ANN

In [37]:
# optimizer: optimizers such as gradiend descent, adam etc.
# loss: loss function of the optimizer
## when binary classsification the loss function is always binary_crossentropy
## when multi-class classsification the loss function is always categorical_crossentropy
# metrics: evaluation metric

ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

## Training the ANN on the training set

In [38]:
# batch_size: instead of compairing prediction to real result one by one,
# compare several predictions with several real values
# epochs: 1 epoch completes when all rows are used to train

ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 4s 4ms/step - loss: 0.6345 - accuracy: 0.7138
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4895 - accuracy: 0.7966
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4394 - accuracy: 0.8103
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4304 - accuracy: 0.8141
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4173 - accuracy: 0.8179
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3823 - accuracy: 0.8386
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3714 - accuracy: 0.8449
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3647 - accuracy: 0.8485
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3582 - accuracy: 0.8508
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3514 - accura

#  Making the predictions and evaluating the model

## Predicting the result of a single observation

**Use our ANN model to predict if the customer with the following informations will leave the bank:**

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

In [43]:
# any input to ann must be 2D array
# pass enciding of France --> 1, 0, 0
# simce output layer is sigmoid, the prediction will be the probabillity of a customer leaving bank
# 0.5 is the threshold

ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5

array([[False]])

Therefore, our ANN model predicts that this customer stays in the bank

## Predicting the test set resulta

In [46]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Making the Confusin Matrix

In [49]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1523   72]
 [ 206  199]]


0.861